### ISSUE TITLE
Feature Suggestion: Add Interactive django shell to run django ORM queries

### ISSUE THREAD

**Issue by shtayeb** [anze3db/django-tui#3]
# Add Interactive django shell to run django ORM queries and show the output

## How it works ?

![638383986838394976](https://github.com/anze3db/django-tui/assets/48182832/b8b1fb3b-4e25-4963-9936-474355c2b869)

### 1

Add another command `python manage.py django-ishell` to launch the interactive shell.

### 2
Integrate it into existing `django-tui` command and have separate screen for it.
![638384053662758328](https://github.com/anze3db/django-tui/assets/48182832/f52b07aa-c5ba-468f-a943-f6cf6970dd54)

## Side Note:
I already have a MVP version of the feature, if you confirm I will create a pull request as soon as possible.

**Comment by shtayeb** [comment]
@anze3db ?

**Comment by anze3db** [comment]
I'm not exactly sure what you mean by interactive shell. How does it differ from `python manage.py shell`? If you have the MVP ready, feel free to open a PR (or send a link to your repo), and I'll check it out.

About the approaches: I'm not a big fan of approach 2 because it would add an extra step to the primary workflow of looking up commands, but maybe we could bind something like ctrl+i to get to the interactive shell?

**Comment by shtayeb** [comment]
Sure, Here is the pr [link](https://github.com/anze3db/django-tui/pull/4).

The main way that it differs from `manage.py shell` is the ease of use. In here you will be writing queries in an editor like environment.

**Quick Demo**

https://github.com/anze3db/django-tui/assets/48182832/88a74dee-c759-4d7b-8ff3-d5857c462d4d

**Comment by anze3db** [comment]
@shtayeb thank you for the contribution ❤️ ! The interactive shell is available in version 23.9 that was just released!
